version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ../data/redis:/data
    restart: always
  web:
    build:
      context: ./
    depends_on:
      - redis
    container_name: web
    ports:
      - "9000:8081"